# Site wide configuration
title: David Amey
description: 'Musings on development, dev-ops and more'
url: https://davidamey.github.io
date_format: '%d/%m/%Y'
fort_awesome_icon: 'cog fa-spin'

# Owner configuration
# name and email are required (change code to remove these)
# (leave the rest blank to disable the corresponding sharing button)
owner:
    name: David Amey
    email: david@amey.org.uk
    github: davidamey
    twitter: davidamey
    linkedin: davidamey
    facebook:
    google_plus: DavidAmey123
    youtube:

# Post sharing icons
sharing:
    twitter: true
    linkedin: true
    facebook: true
    google_plus: true
    reddit: true

# Disqus comments configuration (leave blank to disable comments)
disqus_shortname: 'davidamey'

# Jekyll configuration
permalink: /:year/:month/:day/:title/
paginate: 7

# Markdown
markdown: kramdown
highlighter: rouge

# Enable when using kramdown (you will need to use ~~~ instead of ```)
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

# Gems
gems: ['jekyll-paginate']

# Exclude
exclude: [
  'README.md',
  'create-favicon.sh'
]

